name: linear-regression
channels:
  - conda-forge
dependencies:
  - black=22.6.0
  - flake8=4.0.1
  - isort=5.10.1
  - matplotlib=3.4.2
  - pandas=1.4.2
  - pylint=2.14.4
  - python=3.8
  - tensorflow-cpu=2.8.1
